- app/models/event.rb
- Uncommented the code event.rb
> uncommented the code in event.rb

- Gemfile
- Gemfile.lock
- config/environments/development.rb
- config/routes.rb
- config/storage.yml
- db/migrate/20230612214423_create_active_storage_tables.active_storage.rb
- db/schema.rb
- Added a new gem "cloudinary"
- created .env file with cloudinary_URL
- Install Active storage
- created a new migration file, that created two tables in DB schema
- Changed files storage.yml & environments/development.rb
> Cloudinary

- Gemfile.lock
- db/seeds.rb
Have created seeds for users, attractions, communities, city
> created seeds

- app/channels/chatroom_channel.rb
- app/controllers/chatrooms_controller.rb
- app/controllers/messages_controller.rb
- app/javascript/controllers/chatroom_subscription_controller.js
- app/javascript/controllers/index.js
- app/models/chatroom.rb
- config/routes.rb
- package.json
- test/channels/chatroom_channel_test.rb
- yarn.lock
- Impleted controller actions for chatroom
> created controller for chatroom

- app/controllers/attractions_controller.rb
- app/controllers/categories_controller.rb
- app/controllers/cities_controller.rb
- app/controllers/communities_controller.rb
- app/controllers/events_controller.rb
- app/controllers/posts_controller.rb
- app/models/city.rb
- app/views/attractions/index.html.erb
- app/views/categories/index.html.erb
- app/views/cities/index.html.erb
- app/views/cities/show.html.erb
- app/views/communities/index.html.erb
- app/views/events/index.html.erb
- app/views/posts/index.html.erb
- config/routes.rb
- Added destroy action to the views and controllers
> Added dstroy action to the views and controllers

- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/models/user.rb
- app/views/devise/registrations/new.html.erb
- app/views/layouts/application.html.erb
Signup including all User's fields,  categories not yet fully functioning.
> Devise Setup 

- app/controllers/attractions_controller.rb
- app/controllers/categories_controller.rb
- app/controllers/communities_controller.rb
- app/controllers/events_controller.rb
- app/controllers/posts_controller.rb
- app/views/attractions/edit.html.erb
- app/views/attractions/index.html.erb
- app/views/attractions/new.html.erb
- app/views/categories/edit.html.erb
- app/views/categories/index.html.erb
- app/views/cities/edit.html.erb
- app/views/cities/show.html.erb
- app/views/communities/edit.html.erb
- app/views/communities/index.html.erb
- app/views/events/edit.html.erb
- app/views/events/index.html.erb
- app/views/posts/edit.html.erb
- app/views/posts/index.html.erb
- Implemented edit and update actions for City, Community, Attraction, Post, Event, Categories
> Added edit and update actions

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
> Landing page

- app/models/event.rb
- app/models/user.rb
- app/views/event_categories/index.html.erb
- app/views/event_categories/new.html.erb
- app/views/favorite_categories/index.html.erb
- app/views/favorite_events/index.html.erb
- app/views/favorite_events/new.html.erb
- Added new views for join tables
> New views for join tables

- Gemfile.lock
> bundle-bug

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_map.scss
- app/controllers/attractions_controller.rb
- app/controllers/events_controller.rb
- app/javascript/controllers/map_controller.js
- app/models/attraction.rb
- app/views/attractions/_info_window.html.erb
- app/views/attractions/index.html.erb
- app/views/events/_info_window.html.erb
- app/views/events/index.html.erb
Map showing attractions and pin text boxes.
> attractions map settings

- app/controllers/attractions_controller.rb
- app/controllers/cities_controller.rb
- app/controllers/events_controller.rb
- app/controllers/posts_controller.rb
- app/models/attraction.rb
- app/models/city.rb
- app/models/event.rb
- app/models/post.rb
- app/models/user.rb
- app/views/attractions/edit.html.erb
- app/views/attractions/index.html.erb
- app/views/attractions/new.html.erb
- app/views/cities/edit.html.erb
- app/views/cities/new.html.erb
- app/views/cities/show.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/events/edit.html.erb
- app/views/events/index.html.erb
- app/views/events/new.html.erb
- app/views/pages/home.html.erb
- app/views/posts/edit.html.erb
- app/views/posts/index.html.erb
- app/views/posts/new.html.erb
- config/environments/production.rb
- config/storage.yml
- Added upload image functionality
> Cloudinary next

- app/assets/stylesheets/components/_city_show.scss
- app/assets/stylesheets/components/_navbar.scss
- app/controllers/attractions_controller.rb
- app/controllers/cities_controller.rb
- app/controllers/pages_controller.rb
- app/views/cities/index.html.erb
- app/views/cities/show.html.erb
- app/views/layouts/application.html.erb
- app/views/posts/index.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
> City home page

- app/views/attractions/show.html.erb
- app/views/events/show.html.erb
> Attraction show page

- app/views/posts/show.html.erb
> post show page

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_index_post.scss
- app/views/posts/index.html.erb
> posts index page

- app/controllers/events_controller.rb
- db/seeds.rb
New seeding for events, attractions, cities and users.
> New seeding

- Gemfile.lock
- app/assets/stylesheets/components/_city_show.scss
- app/controllers/cities_controller.rb
- app/views/chatrooms/index.html.erb
- app/views/communities/show.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
- made changes in the city-show page
> Add communities

- app/controllers/communities_controller.rb
- app/views/communities/show.html.erb
> chnages show-communities page

- app/views/cities/index.html.erb
- app/views/shared/_navbar.html.erb
- changes to the cities-index page
- And changed the avatar (user)
> cities index page

- app/assets/stylesheets/components/_footer.scss
> footer problem

- app/views/attractions/edit.html.erb
- app/views/categories/edit.html.erb
- app/views/communities/edit.html.erb
- app/views/posts/edit.html.erb
Added Div and new-form class to edit files in (attractions, posts, communities, and categories)
> Edit files changes 

- app/controllers/chatrooms_controller.rb
- app/controllers/messages_controller.rb
- app/controllers/users_controller.rb
- app/models/chatroom.rb
- app/models/user.rb
- app/views/chatrooms/index.html.erb
- app/views/chatrooms/new.html.erb
- app/views/chatrooms/show.html.erb
- db/migrate/20230619083930_add_user_columns_to_chatroom.rb
- db/schema.rb
- test/controllers/users_controller_test.rb
> backend chat functionality

- app/views/attractions/index.html.erb
- app/views/events/index.html.erb
> Index pages maps removal

- app/controllers/attractions_controller.rb
- app/views/cities/new.html.erb
- app/views/cities/show.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
Different navbar dropdowns displayed options, as well as options to add a new community and attractions on a city show page when the user is an admin.
> User / Admin changes

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/pages/_home.scss
> text color change

- app/assets/stylesheets/components/_chat_page.scss
- app/assets/stylesheets/components/_index.scss
- app/controllers/chatrooms_controller.rb
- app/models/chatroom.rb
- app/models/user.rb
- app/views/chatrooms/index.html.erb
- app/views/chatrooms/new.html.erb
- app/views/chatrooms/show.html.erb
- app/views/layouts/chat.html.erb
- app/views/messages/_message.html.erb
- Implemented chat functionality front-end
> Chat-front-end

- app/assets/stylesheets/components/_footer.scss
> height of footer

- app/assets/stylesheets/components/_card_index.scss
- app/assets/stylesheets/components/_index.scss
- app/controllers/events_controller.rb
- app/controllers/favorite_events_controller.rb
- app/javascript/controllers/events_index_controller.js
- app/views/events/_city_events.html.erb
- app/views/events/_favorite_events.html.erb
- app/views/events/index.html.erb
- app/views/pages/home.html.erb
- config/routes.rb
> changed the front end for events index page

- app/assets/stylesheets/pages/_home.scss
- app/controllers/communities_controller.rb
- app/controllers/posts_controller.rb
- app/models/community.rb
- app/models/post.rb
- app/views/communities/show.html.erb
- app/views/posts/new.html.erb
- db/migrate/20230620145713_add_communityto_post.rb
- db/schema.rb
Added  Community Posts to Comunity showpage
> Community Posts display changes

- app/controllers/events_controller.rb
- app/controllers/favorite_events_controller.rb
- app/models/favorite_category.rb
- app/models/favorite_event.rb
- app/views/favorite_events/index.html.erb
- config/routes.rb
> Favorite_events index

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/_card_index.scss
- app/controllers/events_controller.rb
- app/models/event.rb
- app/views/events/index.html.erb
- added search functionality for events
> Added search functionality to events

- app/views/attractions/index.html.erb
- attractions index page changes are made
> attractions index page

- app/assets/stylesheets/components/_show_users.scss
- app/views/users/show.html.erb
> changes to users page

- app/assets/stylesheets/components/_city_show.scss
- app/assets/stylesheets/components/_event_index.scss
- app/assets/stylesheets/components/_new_edit_form.scss
- app/assets/stylesheets/components/_new_form.scss
- app/controllers/cities_controller.rb
- app/controllers/events_controller.rb
- app/controllers/favorite_events_controller.rb
- app/views/attractions/index.html.erb
- app/views/cities/_new.html.erb
- app/views/cities/index.html.erb
- app/views/cities/new.html.erb
- app/views/shared/_navbar.html.erb
- Made cahnages in nav bar
- fixed the error eith maps on fav_evets
- Added new city in city index page
> mde changes in nav-bar, fav_events index and city index

- app/assets/stylesheets/components/_index.scss
- app/views/events/new.html.erb
> small changes to new events

- app/assets/stylesheets/components/_new_events.scss
- app/views/events/new.html.erb
simple form and css info for the user to create an event
> event new page

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_show_form.scss
- app/controllers/attractions_controller.rb
- app/views/attractions/show.html.erb
- app/views/cities/show.html.erb
- db/seeds.rb
> added show page - not completed

- app/controllers/events_controller.rb
- app/controllers/posts_controller.rb
- app/views/cities/show.html.erb
- app/views/communities/show.html.erb
- app/views/events/new.html.erb
- app/views/posts/_new.html.erb
- app/views/posts/index.html.erb
> added new posts

- app/assets/stylesheets/components/_chat_page.scss
- app/views/chatrooms/new.html.erb
> added form for new chat

- Gemfile
- app/assets/stylesheets/components/_chatroom.scss
> gemfile added redis

- app/assets/stylesheets/components/_chatroom.scss
- app/views/chatrooms/show.html.erb
- app/views/messages/_message.html.erb
> chat styling

- app/assets/stylesheets/components/_new_events.scss
- app/views/events/new.html.erb
> margins and padding fix

- app/assets/stylesheets/components/_communities_posts.scss
- app/views/communities/show.html.erb
- db/seeds.rb
> seeding community events

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
- app/views/shared/_footer.html.erb
- Made changes in landing pages
> landing page changes

- app/assets/stylesheets/components/_city_show.scss
- app/views/cities/show.html.erb
- changed the show page of city
> changed show page for cities

- app/assets/stylesheets/components/_city_show.scss
- app/assets/stylesheets/components/_community_show.scss
- app/assets/stylesheets/components/_index.scss
- app/views/cities/show.html.erb
- app/views/communities/show.html.erb
- Changed the communities show page
-
> changed communities-show-page

- app/assets/stylesheets/components/_event_index.scss
- app/views/pages/home.html.erb
- app/views/posts/index.html.erb
> chnages in all posts
